name: using_one_job_pytest
on: 
  push:
    branches:
      - feature/pytest-failure
  workflow_dispatch:
  
jobs:
  build_test_package:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v7
      - name: python install
        uses: actions/setup-python@v5 
      - name: install python dependencies
        run: pip install -r  requirements.txt
      - name: list
        run: ls
      - name: run ruff  
        run: ruff check .
      
      - name: run pytest
        run: pytest
        
      - name: package creation
        run: zip -r release.zip .

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: ./release.zip

    
      
