name: CI_Main
on:
  pull_request:
    branches:
    - main
  workflow_dispatch: 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v5
      - run: pip install -r requirements.txt
      - run: ls
      - run: ruff check .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v5
      - run: pip install -r requirements.txt
      - run: pytest

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: zip -r release.zip .
      - uses: actions/upload-artifact@v7
        with:
          name: my-artifact
          path: ./release.zip
  deploy:
     needs: package
     runs-on: ubuntu-latest
     steps:
       - uses: actions/downloads-artifact@v7
         with:
           name: my-artifact
       - run: ls
       - uses: appleboy/scp-action@v1 
         with: 
               host: ${{ secrets.HOST_NAME }} 
               username: ${{ secrets.USERNAME }} 
               key: ${{ secrets.KEY }} 
               source: "./release.zip" 
               target: "/opt/fastapi"  

               
       - uses: appleboy/ssh-action@v1 
         with: 
             host: ${{ secrets.HOST_NAME }} 
             username: ${{ secrets.USERNAME }} 
             key: ${{ secrets.KEY }} 
             script: | 
                  cd /opt/fastapi
                  unzip -o ./release.zip
                  systemctl restart fastapi.service
                  sudo systemctl status fastapi --no-page       
